# Generated by Django 5.2.8 on 2025-11-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_audio',
            field=models.FileField(blank=True, help_text='Optional audio introduction', null=True, upload_to='profiles/audio/', verbose_name='Profile Audio'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Optional profile image', null=True, upload_to='profiles/images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_note',
            field=models.TextField(blank=True, help_text='Tell job owners about yourself and why you are interested', verbose_name='Profile Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_video',
            field=models.FileField(blank=True, help_text='Optional video introduction', null=True, upload_to='profiles/video/', verbose_name='Profile Video'),
        ),
    ]
