# Generated by Django 5.2.8 on 2025-11-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_audio_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_deliverable_types',
            field=models.CharField(blank=True, help_text='Default deliverable types for new jobs (comma-separated)', max_length=50, verbose_name='Default Deliverable Types'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_expired_date_days',
            field=models.IntegerField(blank=True, help_text='Default expired date in days for new jobs', null=True, verbose_name='Default Expired Date (Days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_recruit_deadline_days',
            field=models.IntegerField(blank=True, help_text='Default recruit deadline in days for new jobs', null=True, verbose_name='Default Recruit Deadline (Days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_recruit_limit',
            field=models.IntegerField(blank=True, help_text='Default recruit limit for new jobs', null=True, verbose_name='Default Recruit Limit'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_submit_deadline_days',
            field=models.IntegerField(blank=True, help_text='Default submit deadline in days for new jobs', null=True, verbose_name='Default Submit Deadline (Days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_submit_limit',
            field=models.IntegerField(blank=True, help_text='Default submit limit for new jobs', null=True, verbose_name='Default Submit Limit'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_target_dialect',
            field=models.CharField(blank=True, help_text='Default target dialect for new jobs', max_length=100, verbose_name='Default Target Dialect'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_target_language',
            field=models.CharField(blank=True, help_text='Default target language for new jobs', max_length=10, verbose_name='Default Target Language'),
        ),
    ]
