# Generated by Django 5.2.8 on 2025-11-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_default_deliverable_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pretty_name',
            field=models.CharField(blank=True, help_text='Display name shown on the site frontend (e.g., Financiador, Creador)', max_length=255, verbose_name='Pretty Name'),
        ),
    ]
