# Generated by Django 5.2.8 on 2025-11-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_pretty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.TextField(blank=True, help_text='Your wallet address', verbose_name='Wallet Address'),
        ),
    ]
