# Generated by Django 5.2.8 on 2025-11-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_key_id',
            field=models.CharField(blank=True, help_text='Key identifier for seller wallet (marketplace account)', max_length=255, null=True, verbose_name='Seller Key ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_private_key',
            field=models.TextField(blank=True, help_text='Private key (PEM format) for seller wallet authentication', null=True, verbose_name='Seller Private Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_wallet_address',
            field=models.URLField(blank=True, help_text='Open Payments wallet address for seller/marketplace account', max_length=500, null=True, verbose_name='Seller Wallet Address'),
        ),
    ]
