# Generated by Django 5.2.8 on 2025-11-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_seller_key_id_user_seller_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_endpoint',
        ),
    ]
