# Generated by Django 5.2.8 on 2025-11-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('target_field', models.CharField(help_text='Field/UI element that needs audio (e.g., title, description)', max_length=100, verbose_name='Target Field')),
                ('language_code', models.CharField(help_text='Language code for the requested audio', max_length=10, verbose_name='Language Code')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this audio request', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fulfilled At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Audio Request',
                'verbose_name_plural': 'Audio Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'target_field'], name='audio_audio_content_643103_idx'), models.Index(fields=['language_code', 'status'], name='audio_audio_languag_c0a326_idx'), models.Index(fields=['status', 'created_at'], name='audio_audio_status_03c5d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('target_field', models.CharField(help_text='Short slug identifying which field/UI element this audio narrates (e.g., title, description)', max_length=100, verbose_name='Target Field')),
                ('language_code', models.CharField(help_text='Language code for this audio snippet', max_length=10, verbose_name='Language Code')),
                ('transcript', models.TextField(blank=True, help_text='Text transcription of the audio content', verbose_name='Transcript')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('needs_review', 'Needs Review')], default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(help_text='Audio file (MP3, OGG, etc.)', upload_to='audio/snippets/%Y/%m/%d/', verbose_name='Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audio_snippets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Audio Snippet',
                'verbose_name_plural': 'Audio Snippets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'target_field'], name='audio_audio_content_c2550f_idx'), models.Index(fields=['language_code', 'status'], name='audio_audio_languag_abb091_idx')],
                'unique_together': {('content_type', 'object_id', 'target_field', 'language_code')},
            },
        ),
    ]
