# Generated by Django 5.2.8 on 2025-11-08 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_slug', models.CharField(help_text='Slug that identifies the UI element or content that needs audio', max_length=150, verbose_name='Target Identifier')),
                ('target_label', models.CharField(blank=True, help_text='Human readable name for the target that needs audio', max_length=255, verbose_name='Target Label')),
                ('language_code', models.CharField(help_text='Language provided by the contributor', max_length=10, verbose_name='Language Code')),
                ('notes', models.TextField(blank=True, help_text='Optional message from the contributor', verbose_name='Notes')),
                ('file', models.FileField(help_text='Uploaded audio file (MP3, WAV, OGG)', upload_to='audio/contributions/%Y/%m/%d/', verbose_name='Audio File')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='audio.audiorequest', verbose_name='Related Audio Request')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('contributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributed By')),
            ],
            options={
                'verbose_name': 'Audio Contribution',
                'verbose_name_plural': 'Audio Contributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_slug', 'language_code'], name='audio_audio_target__9a9621_idx'), models.Index(fields=['status', 'created_at'], name='audio_audio_status_a2bd11_idx')],
            },
        ),
    ]
