# Generated by Django 5.2.8 on 2025-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiocontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticUIElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Unique identifier for this UI element (e.g., "dashboard_my_money", "form_password")', max_length=100, unique=True, verbose_name='Slug')),
                ('label_es', models.CharField(help_text='The Spanish text that appears in the UI', max_length=255, verbose_name='Spanish Label')),
                ('label_en', models.CharField(blank=True, help_text='Optional English translation', max_length=255, verbose_name='English Label')),
                ('description', models.TextField(blank=True, help_text='Description of what this UI element is', verbose_name='Description')),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('form', 'Form Field'), ('button', 'Button'), ('navigation', 'Navigation'), ('message', 'Message'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static UI Element',
                'verbose_name_plural': 'Static UI Elements',
                'ordering': ['category', 'slug'],
            },
        ),
    ]
