# Generated by Django 5.2.8 on 2025-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_language', models.CharField(help_text='Language code (e.g., nah, oto, es)', max_length=10, verbose_name='Target Language')),
                ('target_dialect', models.CharField(blank=True, help_text='Specific dialect if applicable', max_length=100, verbose_name='Target Dialect')),
                ('deliverable_types', models.CharField(help_text='Comma-separated: text,video,audio,image', max_length=50, verbose_name='Deliverable Types')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Amount in ILP', max_digits=10, verbose_name='Budget')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('funded', 'Funded'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Additional notes about the submission', verbose_name='Note')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='submissions/text/', verbose_name='Text File')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='submissions/video/', verbose_name='Video File')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='submissions/audio/', verbose_name='Audio File')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='submissions/images/', verbose_name='Image File')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Submission',
                'verbose_name_plural': 'Job Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
