# Generated by Django 5.2.8 on 2025-11-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='funded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount that has been funded in ILP', max_digits=10, verbose_name='Funded Amount'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_funded',
            field=models.BooleanField(default=False, help_text='Whether the job has been fully funded', verbose_name='Is Funded'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Interledger payment ID for escrow', max_length=255, null=True, verbose_name='Payment ID'),
        ),
    ]
