# Generated by Django 5.2.8 on 2025-11-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobfunding'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_responses',
            field=models.PositiveIntegerField(default=1, help_text='Number of responses/submissions needed for this job (e.g., if you want 20 people to do the same voice or picture set)', verbose_name='Maximum Responses'),
        ),
    ]
