# Generated by Django 5.2.8 on 2025-11-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_max_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reference_audio',
            field=models.FileField(blank=True, help_text='Optional audio instructions uploaded or recorded by the funder', null=True, upload_to='jobs/reference/audio/', verbose_name='Reference Audio/Instructions'),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional image reference or mood board for the job', null=True, upload_to='jobs/reference/images/', verbose_name='Reference Image'),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_video',
            field=models.FileField(blank=True, help_text='Optional video instructions or inspiration for the job', null=True, upload_to='jobs/reference/video/', verbose_name='Reference Video'),
        ),
    ]
