# Generated by Django 5.2.8 on 2025-11-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_reference_audio_job_reference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='amount_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in ILP to pay each person who completes this job', max_digits=10, null=True, verbose_name='Amount Per Person'),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Total amount in ILP (calculated as amount_per_person ? max_responses)', max_digits=10, verbose_name='Budget'),
        ),
    ]
