# Generated by Django 5.2.8 on 2025-11-09 01:11

from django.db import migrations
from decimal import Decimal


def populate_amount_per_person(apps, schema_editor):
    """Populate amount_per_person for existing jobs."""
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.filter(amount_per_person__isnull=True):
        # For existing jobs, calculate amount_per_person from budget / max_responses
        # If max_responses is 0 or None, default to 1
        max_responses = job.max_responses if job.max_responses and job.max_responses > 0 else 1
        if max_responses > 0:
            job.amount_per_person = job.budget / Decimal(str(max_responses))
        else:
            job.amount_per_person = job.budget
        job.save(update_fields=['amount_per_person'])


def reverse_populate_amount_per_person(apps, schema_editor):
    """Reverse migration - set amount_per_person to None."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.all().update(amount_per_person=None)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_amount_per_person'),
    ]

    operations = [
        migrations.RunPython(populate_amount_per_person, reverse_populate_amount_per_person),
    ]
