# Generated by Django 5.2.8 on 2025-11-09 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_populate_amount_per_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the creator marked their work as complete', null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Whether the creator has marked their work as complete', verbose_name='Work Complete'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('funded', 'Funded'), ('rejected', 'Rejected'), ('waiting_completion', 'Waiting Completion'), ('completed', 'Completed')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_note', models.TextField(blank=True, help_text='Tell the job owner about yourself and why you are interested', verbose_name='Profile Note')),
                ('profile_audio', models.FileField(blank=True, help_text='Optional audio introduction', null=True, upload_to='applications/audio/', verbose_name='Profile Audio')),
                ('profile_video', models.FileField(blank=True, help_text='Optional video introduction', null=True, upload_to='applications/video/', verbose_name='Profile Video')),
                ('profile_image', models.ImageField(blank=True, help_text='Optional profile image', null=True, upload_to='applications/images/', verbose_name='Profile Image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
