# Generated by Django 5.2.8 on 2025-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsubmission_completed_at_jobsubmission_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('funded', 'Funded'), ('rejected', 'Rejected'), ('waiting_completion', 'Waiting Completion'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
