# Generated by Django 5.2.8 on 2025-11-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruit_deadline',
            field=models.DateTimeField(blank=True, help_text='Date and time when recruiting will automatically end and move to selection phase (default: 7 days from creation)', null=True, verbose_name='Recruit Deadline'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruit_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of applications to accept before automatically moving to selection phase', verbose_name='Recruit Limit'),
        ),
        migrations.AddField(
            model_name='job',
            name='submit_deadline',
            field=models.DateTimeField(blank=True, help_text='Date and time when submitting will automatically end and move to review phase (default: 7 days from when submitting phase starts)', null=True, verbose_name='Submit Deadline'),
        ),
        migrations.AddField(
            model_name='job',
            name='submit_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of submissions to accept before automatically moving to review phase', verbose_name='Submit Limit'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('recruiting', 'Recruiting'), ('selecting', 'Selecting'), ('submitting', 'Submitting'), ('reviewing', 'Reviewing'), ('expired', 'Expired'), ('complete', 'Complete'), ('open', 'Open'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('waiting_completion', 'Waiting Completion'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
