# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_recruit_limit_and_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expired_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the job will expire if no applications (in recruiting) or no submissions (in submitting) are received. Wallet contracts expire 7 days after this date.', null=True, verbose_name='Expired Date'),
        ),
    ]
