# Generated by Django 5.2.8 on 2025-11-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submit_deadline_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days from when submitting phase starts until deadline (used to calculate submit_deadline when job transitions to submitting state)', verbose_name='Submit Deadline Days'),
        ),
    ]
