# Generated by Django 5.2.8 on 2025-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_add_submit_deadline_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='funded_amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_funded',
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Interledger payment ID for contract/escrow', max_length=255, null=True, verbose_name='Payment ID'),
        ),
        migrations.DeleteModel(
            name='JobFunding',
        ),
    ]
