# Generated by Django 5.2.8 on 2025-11-09 06:13

from django.db import migrations, models


def convert_legacy_statuses(apps, schema_editor):
    """Convert legacy job statuses to documented statuses."""
    Job = apps.get_model('jobs', 'Job')
    
    # Map legacy statuses to documented statuses
    status_mapping = {
        'open': 'recruiting',           # Open jobs are actively recruiting
        'in_review': 'reviewing',       # In review means reviewing submissions
        'rejected': 'expired',          # Rejected jobs are expired/cancelled
        'waiting_completion': 'reviewing',  # Waiting for completion means reviewing
        'completed': 'complete',        # Just different spelling
        'funded': 'selecting',          # Funded jobs are likely in selection phase
    }
    
    # Convert each legacy status
    for old_status, new_status in status_mapping.items():
        Job.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_remove_funding_fields'),
    ]

    operations = [
        # Convert existing jobs with legacy statuses
        migrations.RunPython(convert_legacy_statuses, migrations.RunPython.noop),
        
        # Update field choices to remove legacy statuses
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('recruiting', 'Recruiting'),
                    ('selecting', 'Selecting'),
                    ('submitting', 'Submitting'),
                    ('reviewing', 'Reviewing'),
                    ('expired', 'Expired'),
                    ('complete', 'Complete'),
                ],
                default='draft',
                max_length=20,
                verbose_name='Status'
            ),
        ),
    ]
