# Generated by Django 5.2.8 on 2025-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_legacy_job_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title_audio',
            field=models.FileField(blank=True, help_text='Optional audio file for the title in the target language', null=True, upload_to='jobs/title_audio/', verbose_name='Title Audio'),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text content entered directly (alternative to file upload)', verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='job',
            name='amount_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in pesos to pay each person who completes this job', max_digits=10, null=True, verbose_name='Amount Per Person'),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Total amount in pesos (calculated as amount_per_person ? max_responses)', max_digits=10, verbose_name='Budget'),
        ),
    ]
