# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_add_text_content_to_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_completed',
            field=models.BooleanField(default=False, help_text='Whether the contract/payment has been completed/released', verbose_name='Contract Completed'),
        ),
    ]
