# Generated by Django 5.2.8 on 2025-11-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_contract_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('recruiting', 'Recruiting'), ('selecting', 'Selecting'), ('submitting', 'Submitting'), ('reviewing', 'Reviewing'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('complete', 'Complete')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
