# Generated by Django 5.2.8 on 2025-11-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_add_canceled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this submission is a draft (not yet submitted)', verbose_name='Is Draft'),
        ),
    ]
