# Generated by Django 5.2.8 on 2025-11-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_add_is_draft_to_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Interledger payment redirect URL for buyer to complete payment",
                max_length=500,
                null=True,
                verbose_name="Payment URL",
            ),
        ),
    ]
