# Generated by Django 5.2.8 on 2025-11-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_add_is_draft_to_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='continue_id',
            field=models.CharField(blank=True, help_text='GNAP continuation access token', max_length=255, null=True, verbose_name='Continue ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='continue_url',
            field=models.URLField(blank=True, help_text='GNAP continuation endpoint', null=True, verbose_name='Continue URL'),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_id',
            field=models.CharField(blank=True, help_text='ULID transaction ID for Open Payments contract', max_length=255, null=True, unique=True, verbose_name='Contract ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='finish_id',
            field=models.CharField(blank=True, help_text='GNAP finish identifier', max_length=255, null=True, verbose_name='Finish ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='incoming_payment_id',
            field=models.URLField(blank=True, help_text='Open Payments incoming payment URL', null=True, verbose_name='Incoming Payment ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='interactive_redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect buyer for wallet authorization', null=True, verbose_name='Interactive Redirect URL'),
        ),
        migrations.AddField(
            model_name='job',
            name='quote_id',
            field=models.URLField(blank=True, help_text='Open Payments quote URL', null=True, verbose_name='Quote ID'),
        ),
        migrations.CreateModel(
            name='PendingPaymentTransaction',
            fields=[
                ('contract_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('buyer_wallet_data', models.JSONField(help_text='Serialized buyer wallet address data', verbose_name='Buyer Wallet Data')),
                ('seller_wallet_data', models.JSONField(help_text='Serialized seller wallet address data', verbose_name='Seller Wallet Data')),
                ('incoming_payment_id', models.URLField(blank=True, null=True, verbose_name='Incoming Payment ID')),
                ('quote_id', models.URLField(blank=True, null=True, verbose_name='Quote ID')),
                ('interactive_redirect', models.URLField(blank=True, null=True, verbose_name='Interactive Redirect URL')),
                ('finish_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Finish ID')),
                ('continue_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Continue ID')),
                ('continue_url', models.URLField(blank=True, null=True, verbose_name='Continue URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transaction', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Pending Payment Transaction',
                'verbose_name_plural': 'Pending Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
