# Generated by Django 5.2.8 on 2025-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_continue_id_job_continue_url_job_contract_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpaymenttransaction',
            name='hash_value',
            field=models.CharField(blank=True, help_text='Hash value from wallet authorization callback for verification', max_length=255, null=True, verbose_name='Hash Value'),
        ),
        migrations.AddField(
            model_name='pendingpaymenttransaction',
            name='interact_ref',
            field=models.CharField(blank=True, help_text='GNAP interact reference from wallet authorization callback', max_length=255, null=True, verbose_name='Interact Ref'),
        ),
    ]
